// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6PoQNII_Y-p7ydvcUzTL26VNe4GT71Zc',
    appId: '1:80078589156:web:4767afd8b5845d3c3e30f1',
    messagingSenderId: '80078589156',
    projectId: 'chat-92d56',
    authDomain: 'chat-92d56.firebaseapp.com',
    storageBucket: 'chat-92d56.appspot.com',
    measurementId: 'G-YW5EG1LDRL',
  );

  static const FirebaseOptions android = FirebaseOptions(
      apiKey: 'AIzaSyBSep7Vak2WP7Gb9qNlVKY3fb0y6pZqNrs',
      appId: '1:882651731701:android:cba141db54ba3f030517bc',
      messagingSenderId: '882651731701',
      projectId: 'klicks-2252e',
      storageBucket: 'klicks-2252e.appspot.com');

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHJ7QClnIy_zM4-eQyRjuUuqx62wWiR6s',
    appId: '1:80078589156:ios:0bf807b81beea1523e30f1',
    messagingSenderId: '80078589156',
    projectId: 'chat-92d56',
    storageBucket: 'chat-92d56.appspot.com',
    iosClientId:
        '80078589156-od1eglniccojel1ob9hjtvsuo2ngikkf.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHJ7QClnIy_zM4-eQyRjuUuqx62wWiR6s',
    appId: '1:80078589156:ios:0bf807b81beea1523e30f1',
    messagingSenderId: '80078589156',
    projectId: 'chat-92d56',
    storageBucket: 'chat-92d56.appspot.com',
    iosClientId:
        '80078589156-od1eglniccojel1ob9hjtvsuo2ngikkf.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
